config/routes.rb
Rails.application.routes.draw do
  get 'registry/index'

  get 'welcome/index'
  get 'welcome/show'
  get 'registry/index'
  get 'user_entry' => 'guestbooks#user_entry'

  resources :regrets
  devise_for :users
  resources :guestbooks

  root 'welcome#index'
  get 'user_root' => 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/guestbook.rb
class Guestbook < ApplicationRecord
	belongs_to :user	

	resourcify
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  before_action :set_guestbook, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, except: [:show]

  # GET /guestbooks
  # GET /guestbooks.json
  def index
    @guestbooks = Guestbook.page(params[:page]).per(3).all
  end

  # GET /guestbooks/1
  # GET /guestbooks/1.json
  def show
  end

  # GET /guestbooks/new
  def new
    @guestbook = Guestbook.new
  end

  # GET /guestbooks/1/edit
  def edit
  end

  def user_entry
  end
  
  # POST /guestbooks
  # POST /guestbooks.json
  def create
    @guestbook = Guestbook.new(guestbook_params)

    respond_to do |format|
      if @guestbook.save
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully created.' }
        format.json { render :show, status: :created, location: @guestbook }
      else
        format.html { render :new }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guestbooks/1
  # PATCH/PUT /guestbooks/1.json
  def update
    respond_to do |format|
      if @guestbook.update(guestbook_params)
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @guestbook }
      else
        format.html { render :edit }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.json
  def destroy
    @guestbook.destroy
    respond_to do |format|
      format.html { redirect_to guestbooks_url, notice: 'Guestbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestbook
      @guestbook = Guestbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestbook_params
      params.require(:guestbook).permit(:user_id, :message)
    end

    def check_admin
      unless current_user.role == "admin"
        flash[:alert] = "Access denied. If you feel this error is incorrect, please contact the system administrator."
        redirect_to user_root_path
      end
    end
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/views/guestbooks/_form.html.erb
  <%= form_for(guestbook) do |f| %>
    <% if guestbook.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

        <ul>
        <% guestbook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="cant-see-me">
      <%= f.number_field :user_id, value: current_user.id %>
    </div>
    <div class="container-fluid">
      <form class="form-horizontal">
        <div class="form-group">
          <%= f.text_area :message, placeholder: "Leave a message for the bride and groom.", class: "big-forms submit" %>
          <br>
          <%= f.submit :class => "submit btn-semi-mini leave-message" %>
        </div>
      </form>
    </div>

  <% end %>

app/views/guestbooks/edit.html.erb
<div class="container-fluid center-block">
	
	
	<div class="btn-group ">

	</div>
</div>

<div class="row">
	<h1 class="title">Edit Your Message</h1>
	<div class="panel panel-default panel-trans">
		<%= render 'form', guestbook: @guestbook %>
		<div class="panel-footer panel-trans">
			<%= link_to 'Show', @guestbook, class: 'btn btn-semi-mini' %> 
			<%= link_to 'Back', guestbooks_path, class: 'btn btn-semi-mini' %>
		</div>
	</div>
</div>

app/views/guestbooks/index.html.erb
<div class="container-fluid">
  <h2 class="title">Messages for Jessica and William</h2>

    <%= link_to 'Leave a Note', new_guestbook_path, class: 'btn btn-default' %>
  <br>
  <%= paginate @guestbooks %>
  <div class="row">
    <% @guestbooks.each do |guestbook| %>
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading panel-turq">
            <%= guestbook.user.name %> says:
          </div>
          <div class="panel-body panel-turq">
            <%= guestbook.message[0..250] %>... <%= link_to 'Read More', guestbook %>
          </div>
          <% if current_user.id == guestbook.user.id %>
            <div class="panel-footer panel-turq">
              <div class="btn-group btn-group-small">
                <% if current_user.id == guestbook.user.id %>
                  <%= link_to 'Edit', edit_guestbook_path(guestbook), class: 'btn btn-default' %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/guestbooks/new.html.erb
<div class="container-fluid">
	<h1 class="title"> Sign Jessica and William's Guestbook </h1>
	<%= render 'form', guestbook: @guestbook %>
	<%= link_to 'Back', guestbooks_path, class: "btn-semi-mini submit" %>
</div>

app/views/guestbooks/show.html.erb
<div class="page-header" style="padding-top: 5%">
	<h1 class="title"><%= @guestbook.user.name %> said:</h1>
</div>
<div class="container-fluid">
	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-body panel-turq">
				<%= @guestbook.message %>
			</div>
			<div class="panel-footer panel-turq">
				<div class="btn-group btn-group-small">
					<% if current_user.id == @guestbook.user.id %>
						<%= link_to 'Edit', edit_guestbook_path(@guestbook), class: "btn btn-semi-mini" %> 
					<% end %>
					<%= link_to 'Back', guestbooks_path, class: "btn btn-semi-mini" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/guestbooks/user_entry.html.erb
<% current_user.guestbooks.each do |entry| %>

	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-body panel-turq">
				<%= entry.message %>
			</div>
			<div class="panel-turq panel-footer">
				<%= link_to 'Edit', edit_guestbook_path(entry), class:'btn btn-semi-mini' %>
			</div>
		</div>
	</div>
<% end %>