config/routes.rb
Rails.application.routes.draw do
  get 'registry/index'

  get 'welcome/index'
  get 'welcome/show'
  get 'registry/index'
  get 'user_entry' => 'guestbooks#user_entry'

  resources :regrets
  devise_for :users
  resources :guestbooks

  root 'welcome#index'
  get 'user_root' => 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/regret.rb
class Regret < ApplicationRecord

	belongs_to :user

	resourcify
end

app/controllers/regrets_controller.rb
class RegretsController < ApplicationController
  before_action :set_regret, only: [:show, :edit, :update, :destroy]

  # GET /regrets
  # GET /regrets.json
  def index
    @regrets = Regret.page(params[:page]).per(3).all
  end

  # GET /regrets/1
  # GET /regrets/1.json
  def show
  end

  # GET /regrets/new
  def new
    @regret = Regret.new
  end

  # GET /regrets/1/edit
  def edit
  end

  # POST /regrets
  # POST /regrets.json
  def create
    @regret = Regret.new(regret_params)

    respond_to do |format|
      if @regret.save
        format.html { redirect_to @regret, notice: 'Regret was successfully created.' }
        format.json { render :show, status: :created, location: @regret }
      else
        format.html { render :new }
        format.json { render json: @regret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regrets/1
  # PATCH/PUT /regrets/1.json
  def update
    respond_to do |format|
      if @regret.update(regret_params)
        format.html { redirect_to @regret, notice: 'Regret was successfully updated.' }
        format.json { render :show, status: :ok, location: @regret }
      else
        format.html { render :edit }
        format.json { render json: @regret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regrets/1
  # DELETE /regrets/1.json
  def destroy
    @regret.destroy
    respond_to do |format|
      format.html { redirect_to regrets_url, notice: 'Regret was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regret
      @regret = Regret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regret_params
      params.require(:regret).permit(:user_id, :message)
    end
end

app/helpers/regrets_helper.rb
module RegretsHelper
end

app/views/regrets/_form.html.erb
<%= form_for(@regret) do |f| %>
  <% if @regret.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(regret.errors.count, "error") %> prohibited this regret from being saved:</h2>

      <ul>
      <% regret.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field cant-see-me">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="container-fluid">
      <form class="form-horizontal">
        <div class="form-group">
          <%= f.text_area :message, placeholder: "Leave a message for the bride and groom.", class: "big-forms submit" %>
            <%= f.submit :class => "submit btn-semi-inline" %>
        </div>
      </form>
    </div>
<% end %>

app/views/regrets/edit.html.erb
<div class="container-fluid">
	<h1 class="title">Edit Your Message</h1>

	<%= render 'form', regret: @regret %>

	<%= link_to 'Show', @regret, class: "btn-semi-mini submit" %> 
	<%= link_to 'Back', regrets_path, class: "btn-semi-mini submit" %>

</div>

app/views/regrets/index.html.erb
<div class="container-fluid">
  <h1 class="title">Well Wishes and Regrets</h1>

  <%= paginate @regrets %>
  <div class="row">
    <% @regrets.each do |regret| %>
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= regret.user.name %> said:
          </div>
          <div class="panel-body panel-turq">
            <%= regret.message[0..250] %>...<%= link_to "Read More", regret %>
          </div>

          <div class="panel-footer panel-turq">
            <% if current_user.id == regret.user.id %>
              <%= link_to "Edit", edit_regret_path(regret), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/regrets/new.html.erb
<div class="container-fluid">
	<h1 class="title">Well Wishes for Jessica and William</h1>
	
	<%= render 'form', regret: @regret, button_name: "Leave a Message" %>

	<%= link_to 'Back', regrets_path, class: "btn-semi-mini submit" %>
</div>

app/views/regrets/show.html.erb
<div class="container-fluid">
	<h1 class="title"><%= @regret.user.name %> said:</h1>
	<div class="panel panel-default">
		<div class="panel-body panel-turq">
			<%= @regret.message %>
		</div>
		<div class="panel-footer panel-turq">
			<div class="btn-group">
				<% if current_user.id == @regret.user.id %>
					<%= link_to 'Edit', edit_regret_path(@regret), class: "btn btn-default" %>
				<% end %>
				<%= link_to 'Back', regrets_path, class: "btn btn-default" %>
			</div>
		</div>
	</div>
</div>