config/routes.rb
Rails.application.routes.draw do
  get 'registry/index'

  get 'welcome/index'
  get 'welcome/show'
  get 'registry/index'
  get 'user_entry' => 'guestbooks#user_entry'

  resources :regrets
  devise_for :users
  resources :guestbooks

  root 'welcome#index'
  get 'user_root' => 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/views/layouts/_footer.html.erb
<footer>
	<div class="navbar navbar-inverse navbar-fixed-bottom">
		<div class="container">
			<p class="navbar-text pull-left">
				&#0169; 2017 - Site built by Mary Moody
			</p>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="197">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', welcome_show_path %></li>
      <li><%= link_to 'Guestbook', guestbooks_path %></li>
      <li><%= link_to 'Regrets', regrets_path %></li>
    </ul>
    <div class="nav pull-right btn-group btn-group-sm" style="padding-top: .5%">
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-semi-mini" %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-semi-mini" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="google-site-verification" content="kye5tbHPOxTKFyUlz9tLtimnIhSXkdG3pVuaUnnVYc8" />
  	<%= csrf_meta_tags %>
  	<title>The Arroyo/Wagner Guestbook</title>

  	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"%>
  	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => "reload" %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => "reload" %>
  	<%= javascript_include_tag "http://code.jquery.com/jquery-1.11.3.min.js" %>
  	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
  </head>

  <% if current_page?(root_path) || current_page?(user_root_path) || current_page?(new_user_registration_path) || current_page?(new_user_session_path) || current_page?(welcome_show_path) %>
    <body class="front_page">
      <%= yield %>
    </body>
  <% else %>
    <body>
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </body>
  <% end %>
</html>